# Generated by Django 3.1.3 on 2021-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='choice_id',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
    ]
