# Generated by Django 3.1.3 on 2021-06-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20210603_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='lesson',
        ),
    ]
